#!/usr/bin/env zsh

case ${HOST} in
    retina)
        DP=eDP1
        OUT=DP1
        MODE=1280x800
        SCALE=2x2
        ;;
    mbp)
        DP=LVDS1
        OUT=DP1
        MODE=1280x800
        SCALE=1x1
        ;;
    *)
        echo "unknown laptop: ${HOST}"
        return 1
        ;;
esac

case "$1" in
    off)
        set -x
        xrandr --output ${OUT} --off
        ;;
    right)
        set -x
        xrandr --output ${OUT} --mode ${MODE} --scale ${SCALE} --right-of ${DP}
        ;;
    left)
        set -x
        xrandr --output ${OUT} --mode ${MODE} --scale ${SCALE} --left-of ${DP}
        ;;
    *)
        set -x
        xrandr --output ${OUT} --mode ${MODE} --scale ${SCALE} --same-as ${DP}
        ;;
esac

# Local Variables:
# mode: zsh
# End:
