#!/usr/bin/env zsh

echo initialize dotfiles
DOTFILES=`dirname $0`/../../
DOTFILES=`readlink -e $DOTFILES`
ln -sf $DOTFILES/.zshrc ~/
ln -sf $DOTFILES/.zshenv ~/
ln -sf $DOTFILES/.gitconfig ~/
ln -sf $DOTFILES/.tmux.conf ~/
ln -sf $DOTFILES/.zsh.d/ ~/

# Local Variables:
# mode: zsh
# End:
