#!/usr/bin/env zsh
#set -x

echo initialize dotfiles
DOTDIR=~/etc
DOTFILES=(.zshrc .zshenv .gitconfig .tmux.conf)
for f in $DOTFILES; do
    echo creating link $f
    ln -sf ${DOTDIR}/$f ~/
done

# Local Variables:
# mode: zsh
# End:
