#!/usr/bin/env zsh

if [ $# != 1 ]; then
    echo "usage: echod port";
    return 1;
fi

echo "Listning ${1}"
while true; do
    nc -l -p ${1} -c 'xargs -n1 echo'
    test $? -ne 0 && break;
done

# Local Variables:
# mode: sh
# End:
