#!/usr/bin/env zsh

if [ $# != 1 ]; then
    echo "usage: x file";
    return 2;
fi

local file=$1;
local ext=${file##*.};
local base=${file%.${ext}};

if [ ${ext:u} = "GZ" -o ${ext:u} = "BZ2" -o ${ext:u} = "LZMA" ]; then
    local ext2=${base##*.};
    if [ ${ext2:u} = "TAR" -o ${ext2:u} = "STAR" ]; then
        ext=${ext2}.${ext};
    fi
fi

case "${ext:u}" in
    "GZ")
        gunzip -dc "$file" > "${base}";
        ;;
    "BZ2")
        bunzip2 -dk "$file"
        ;;
    "LZMA")
        lzma -dk "$file"
        ;;
    "TAR")
        tar xvf "$file"
        ;;
    "TGZ"|"TAR.GZ")
        tar xvzf "$file"
        ;;
    "TAR.BZ2")
        tar xvjf "$file"
        ;;
    "TAR.LZMA")
        # for old tar
        lzma -dc "$file" | tar xv;
        ;;
    "ZIP")
        unzip "${file}" -d "${base}"
        ;;
    "CPIO")
        mkdir "${base}"
        pushd "${base}"
        cpio -i < "../$file"
        popd
        ;;
    "LZH")
        mkdir "${base}"
        pushd "${base}"
        lha x "../${file}"
        popd
        ;;
    "DEB")
        mkdir "${base}"
        pushd "${base}"
        ar vx "../${file}"
        x control.tar.gz
        x data.tar.xz
        popd
        ;;
    "RPM")
        mkdir "${base}"
        pushd "${base}"
        rpm2cpio "../${file}" | cpio -idv
        popd
        ;;
    *)
        echo "unsupported archive: ${ext:u}"
        ;;
esac

# Local Variables:
# mode: sh
# End:
