#!/usr/bin/env zsh

autoload -U colors && colors

COLOR_NAMES=(
    black
    red
    green
    yellow
    blue
    magenta
    cyan
    white
    brightblack
    brightred
    brightgreen
    brightyellow
    brightblue
    brightmagenta
    brightcyan
    brightwhite
)

for i in {0..7}; do
    echo -ne "\x1b[48;5;${i}m"
    echo -ne "${COLOR_NAMES[$i + 1]}"
    for s in {0..$(( 22 - ${#COLOR_NAMES[$i + 1]} ))}; do
        echo -ne " "
    done
    j=$((${i} + 8))
    echo -ne "\x1b[48;5;${j}m"
    echo -ne "${COLOR_NAMES[$j + 1]}"
    for s in {0..$(( 22 - ${#COLOR_NAMES[$j + 1]} ))}; do
        echo -ne " "
    done
    echo -ne "\x1b[0m"
    echo
done
echo

# 256 colors
for ((f = 0; f < 255; f++)); do
    printf "\e[38;5;%dm %3d*■\e[m" $f $f
    if [[ $f%8 -eq 7 ]] then
       printf "\n"
    fi
done
echo

# Local Variables:
# mode: sh
# End:
